name: example
description: "An example project for Rabbit."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rabbit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

rabbit:
  pipeable: true
  docs: true
  widgets:
    package:flutter/material.dart:
      - Directionality
      - Opacity
      - ClipRRect
      - Transform
      - Padding
      - Align
      - Center
      - SizedBox
      - ConstrainedBox
      - FractionallySizedBox
      - SliverToBoxAdapter
      - Positioned
      - PositionedDirectional
      - Flexible
      - Expanded
      - TableCell
      - GestureDetector
      - DecoratedBox
      - Container
      - Hero
      - Banner
      - PreferredSize
      - InkWell
      - ElevatedButton
      - FilledButton
      - OutlinedButton
      - TextButton
      - FloatingActionButton
      - Tab
      - Card
      - Dialog
