name: rabbit
description: Rabbit helps you create these wrapper widgets quickly and consistently, maintaining all the original widget's parameters while allowing you to customize what you need.
version: 0.1.0
homepage: https://github.com/dickermoshe/rabbit
repository: https://github.com/dickermoshe/rabbit

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^6.4.1
  args: ^2.6.0
  checked_yaml: ^2.0.3
  cli_completion: ^0.5.0
  cli_util: ^0.4.1
  code_builder: ^4.10.0
  collection: ^1.18.0
  custom_lint_builder: ">=0.6.4 <0.8.0"
  dart_style: ^2.3.6
  json_annotation: ^4.9.0
  mason_logger: ^0.2.16
  path: ^1.9.0
  pub_updater: ^0.4.0
  pubspec_parse: ^1.4.0
  recase: ^4.1.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  build_version: ^2.1.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: 1.25.2
  test_descriptor: ^2.0.2

executables:
  rabbit:
