name: widget_wrapper
description: Customize you favorite widgets by wrapping them.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.0
  pub_updater: ^0.4.0
  path: ^1.9.0
  analyzer: ^6.4.0
  custom_lint_builder: ^0.7.0
  dart_style: ^2.3.7
  pubspec_parse: ^1.4.0
  cli_util: ^0.4.2
  yaml: ^3.1.3
  code_builder: ^4.10.1
  recase: ^4.1.0
  json_annotation: ^4.9.0
  checked_yaml: ^2.0.3
  collection: ^1.19.1

dev_dependencies:
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  build_version: ^2.1.1
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  test: ^1.25.8
  test_descriptor: ^2.0.2

executables:
  widget_wrapper:
